# $FreeBSD: src/etc/defaults/Makefile,v 1.5.2.1 2005/11/23 18:03:32 emax Exp $

FILES=  atrun.plist newsyslog.plist periodic_daily.plist periodic_weekly.plist periodic_monthly.plist tz_adjust.plist save_entropy.plist 
NO_OBJ=
FILESDIR= /etc/launchd/crone
FILESMODE= 444

.include <bsd.prog.mk>
