
FILES= 	abi.sh addswap.sh amd.sh archdep.sh atm1.sh atm2.sh atm3.sh \
	bgfsck.sh bluetooth.sh chgname.sh cleanvar.sh cleartmp.sh devfs.sh \
	dhclient.sh dmesg.sh dumpon.sh early.sh encswap.sh fsck.sh gbde.sh \
	geli.sh geli2.sh hcsecd.sh hcstname.sh hostname.sh initrandom.sh \
	ip6addrctl.sh ip6fw.sh ipfilter.sh ipfs.sh ipfw.sh ipnat.sh ipsec.sh \
	isdnd.sh kldxref.sh ldconfig.sh mixer.sh motd.sh mountcritlocal.sh \
	mountcritremote.sh msgs.sh netif.sh netoptions.sh network_ipv6.sh \
	newsyslog.sh nfsclient.sh nfsserver.sh nisdomain.sh nsswitch.sh \
	ntpdate.sh pccard.sh pcvt.sh pf.sh pfsync.sh power_profile.sh \
	ramdisk-own.sh ramdisk.sh random.sh resolv.sh root.sh routing.sh \
	savecore.sh securelevel.sh sendmail.sh serial.sh sppp.sh sshd.sh \
	syscons.sh sysctl.sh syslogd.sh tmp.sh ugidfw.sh var.sh virecover.sh

FILESDIR=       /etc/launchd/scripts
FILESMODE=      ${BINMODE}

.include <bsd.prog.mk>
