# $FreeBSD: src/etc/defaults/Makefile,v 1.5.2.1 2005/11/23 18:03:32 emax Exp $

FILES=  abi.plist amd.plist atm1.plist accounting.plist apm.plist atm2.plist \
        addswap.plist apmd.plist atm3.plist adjkerntz.plist archdep.plist \
	bgfsck.plist bootparams.plist bluetooth.plist bsnmpd.plist ccd.plist \
	cleanvar.plist cleartmp.plist cron.plist devd.plist devfs.plist \
	dhclient.plist dmesg.plist dumpon.plist early.sh.plist encswap.plist \
	fsck.plist ftpd.plist gbde.plist geli.plist geli2.plist hcsecd.plist \
	hostapd.plist hostname.plist ike.plist ipfilter.plist ipsec.plist \
	inetd.plist ipfs.plist ipxrouted.plist initrandom.plist ipfw.plist \
	isdnd.plist ip6addrctl.plist ipmon.plist ip6fw.plist ipnat.plist \
	kadmind.plist kerberos.plist keyserv.plist kldxref.plist \
	kpasswdd.plist ldconfig.plist lpd.plist mixer.plist motd.plist \
	mountcritlocal.plist mountcritremote.plist mountd.plist moused.plist \
	mroute6d.plist mrouted.plist msgs.plist named.plist natd.plist \
	netif.plist netoptions.plist network_ipv6.plist newsyslog.plist \
	nfsclient.plist nfsd.plist nfsserver.plist nisdomain.plist \
	nsswitch.plist ntpd.plist ntpdate.plist pccard.plist pcvt.plist \
	pf.plist pflog.plist pfsync.plist power_profile.plist powerd.plist \
	ppp.plist pppoed.plist pwcheck.plist quota.plist ramdisk-own.plist \
	ramdisk.plist random.plist rarpd.plist resolv.plist root.plist \
	route6d.plist routed.plist routing.plist rpc_lockd.plist \
	rpc_statd.plist rpcbind.plist rtadvd.plist rwho.plist \
	savecore.plist sdpd.plist securelevel.plist sendmail.plist \
	serial.plist sppp.plist sshd.plist swap1.plist syscons.plist \
	sysctl.plist syslogd.plist timed.plist tmp.plist ugidfw.plist \
	usbd.plist var.plist virecover.plist watchdogd.plist \
	wpa_supplicant.plist ypbind.plist yppasswdd.plist ypserv.plist \
	ypset.plist ypupdated.plist ypxfrd.plist 

NO_OBJ=
FILESDIR= /etc/launchd/rc_plist
FILESMODE= 444

.include <bsd.prog.mk>
